language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# commands to install with dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -e ."

# command to run tests
script: python -m pytest
