version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - test:
          name: "Python 3.14"
          v: "3.14"
      - test:
          name: "Python 3.13"
          v: "3.13"
      - test:
          name: "Python 3.12"
          v: "3.12"
      - test:
          name: "Python 3.11"
          v: "3.11"
      - test:
          name: "Python 3.10"
          v: "3.10"
      - test:
          name: "Python 3.9"
          v: "3.9"

jobs:
  test:
    parameters:
      v:
        type: string
        default: "latest"
    docker:
      - image: cimg/python:<< parameters.v >>
    steps: &steps
      - checkout
      - run:
          name: Install tox
          command: |
            pip install --upgrade pip
            pip install tox

      - run:
          name: Run tox for this Python version
          command: tox -e py<< parameters.v >>
